<script>
    //PushupSocial snippet
    (function (p, s, h) {
        (p[s] = p[s] || []).push(["_setAccount", "<?php echo $communityId ?>"], ["_setCDN", h], ["_setUrl", "http://node.pushup.com"], ["_displayBar"]);
        s = (p = p.document).createElement("script");
        s.src = h + "/pushup.min.js";
        p.getElementsByTagName("head")[0].appendChild(s);
    })(window, "_pa", "http://node.pushup.com/min");