<div class="pushup-social-panel">
    <img class="pushup-social-logo" src="https://8988ae2adffa1e70c1be-11fb47457486c774da6409c1700eb468.ssl.cf2.rackcdn.com/pushup-logo.png"/>

    <p class="pushup-social-description">Add a social network or community to your existing website in minutes! Build
        and grow “your own” community on “your own” website without having to rebuild or redesign your website.</p>

    <p>
        <a class="pushup-social-conversion-btn" role="button" target="_blank" href="<?php echo PushupSocial::LINK_JOIN ?>">Sign up</a>
        <a class="pushup-social-conversion-btn blue" role="button" href="plugins.php?page=<?php echo PUSHUP_PAGESLUG_CONFIG; ?>">I have my code</a>
    </p>

    <p><a role="button" class="pushup-social-learn-more" target="_blank" href="http://pushup.com">Learn More</a></p>

</div>
