<div class="pushup-social-panel">
    <img class="pushup-social-logo" src="http://pushup.com/img/logo.png"/>

    <p class="pushup-social-description">Add a social network or community to your existing website in minutes! Build
        and grow “your own” community on “your own” website without having to rebuild or redesign your website.</p>

    <p><a class="pushup-social-conversion-btn" role="button" target="_blank"
          href="<?php echo PushupSocial::LINK_JOIN ?>">Get Started</a></p>

    <p><a role="button" class="pushup-social-learn-more" target="_blank" href="http://pushup.com">Learn More</a></p>

</div>
<a href="plugins.php?page=<?php echo PUSHUP_PAGESLUG_CONFIG; ?>">I already have a community</a>